language: python
python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  #Install a mini version of anaconda such that we can easily install our dependencies
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy=1.9 scipy=0.16 matplotlib nose sphinx pip nose
  #- pip install . 
  - python setup.py build_ext --inplace
  #--use-mirrors
  #
# command to run tests, e.g. python setup.py test
script: 
  - nosetests GPy/testing
